# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='descripcion',
        ),
    ]
