# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_remove_ciudad_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
