# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.ciudad'),
            preserve_default=False,
        ),
    ]
