# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.sede')),
            ],
        ),
        migrations.DeleteModel(
            name='especialidad',
        ),
    ]
