# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20171118_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='Especialidad',
            field=models.CharField(choices=[('trx', 'trx'), ('funcional', 'funcional'), ('culturismo', 'culturismo'), ('powerlifter', 'powerlifter')], default='trx', max_length=255),
        ),
    ]
