# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_entrenador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, upload_to=b'')),
                ('telefono', models.CharField(max_length=7)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.sede')),
            ],
        ),
        migrations.CreateModel(
            name='salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('tipo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.salon'),
        ),
    ]
