# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20171118_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.sede'),
            preserve_default=False,
        ),
    ]
