# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_auto_20171118_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(),
        ),
    ]
