# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0016_auto_20171118_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.estudiante')),
            ],
        ),
    ]
